### ISSUE TITLE
Test discovery in Visual Studio

### ISSUE THREAD

**Issue by goldenbeard** [chadly/xUnit-BDD-Extensions#7]
Hi,
I really like the way that xUnit.BDD is structured, the syntax is clear and concise.
I'm having problems getting the tests to show up in the Visual Studio test explorer UI. Is this a known issue or is this just not supported?
Running the tests through the xUnit console runner works just fine.
Thanks.

Versions in use:
xUnit 2.3.1
xUnit.BDD: 4.0.2
Visual Studio Pro 2017 15.6.5

**Comment by goldenbeard** [comment]
Hi I think I have solved this.
The problem was I missed installing the xunit.runner.visualstudio package.
I'm running resharper which found and ran the tests OK, as did the xunit console runner, but the visual studio test UI discovered standard xunit tests (but it turns out wasn't able to run them) but xunit.bdd tests were not even discovered in VS Test UI without the runner package.

**Comment by chadly** [comment]
Ahh, great. Yes, you need that package.

Thanks for reporting back!
